<募集詳細/マイページ編集/認証周り>細かい修正とデザイン修正
nagayamajun/unite-replace-front pull request #1
Opened 2023-05-20 06:56 UTC by nagayamajun

マイページに関してですがマイページに遷移後再読み取りをするとエラーが出てしまいます。
デザインに関してはデザインがない為ちょくちょく変更されていません！
また、自分のrecruitsを全件取得するapiがなかった為そこはコメントアウトしています🙇‍♀️

2023-05-20 15:28 UTC, ponsAoki requested changes
実装ありがとうございます！
マークアップ部分の確認と動作確認はできてないんですけど、一旦コメント残します！

2023-05-20 15:28 UTC, ponsAoki commented on src/modules/recruit/recruit.repository.ts
> +  console.log("りクルーター",recruitId);
必要なさそうな`console.log()`削除で🙏

2023-05-20 15:28 UTC, ponsAoki commented on src/components/templetes/user/RecruitDetail.tsx
> +  //   hackthonName?: string;
コメント必要なさそうなものは削除で🙏 (意図的に残してたらすみません！)

2023-05-26 17:27 UTC, ponsAoki requested changes
@nagayamajun 
実装ありがとうございます！
動作確認もされてると思うんで、大体大丈夫だと思います！

2023-05-26 17:27 UTC, ponsAoki commented on src/hooks/useCorporateAuth.ts
>          const ref = doc(db, `corporations/${authCorporation.uid}`);
firebaseの記述削除でお願いします！ (もう多分使う可能性少ないですよね？)

2023-05-27 01:53 UTC, nagayamajun commented on src/hooks/useCorporateAuth.ts
>          const ref = doc(db, `corporations/${authCorporation.uid}`);
そうですね！多分もう使わないと思います！

2023-05-27 01:56 UTC, merged