[FE]企業側の認証機能とsidebarなどのUI作成
nagayamajun/unite-replace-front pull request #21
Opened 2023-07-09 04:53 UTC by nagayamajun

--概要
認証機能を作成しました。

--懸念点
.envとenv.tsがぐちゃぐちゃになって.envから直接呼び出しました。

2023-07-09 06:15 UTC, ponsAoki requested changes
@nagayamajun 
バックエンドがまだPR上がってないと思うんで動作確認はできてないんですけど、コードだけ見た感じで数点コメントしました！
確認お願いします🙇

2023-07-09 06:15 UTC, ponsAoki commented on src/constants/env.ts
> +export const corporateTechUniPassword = process.env.NEXT_PUBLIC_TECH_UNI_PASSWORD;
src/libs/firebase.tsでprocess.env.HOGE使って直接呼び出すなら、ファイルごと削除でいい気がします！
このexportした変数をsrc/libs/firebase.tsで呼び出して、userの方とそろえるのもあり

2023-07-09 06:15 UTC, ponsAoki commented on src/components/organisms/ProductCard.tsx
> +  const participants = participantsInfo?.filter((res) => res.isApproved).map((res) => res.user);
ここ処理自体は間違ってないと思うんですけど、BEの方で「recruitIdから、そのrecruitに参加確定しているuser情報の取得をするapi」を作って、それをカスタムフック経由で呼び出す形でもいいのかなと思いました！
まあでもこれは正直個人的にその方がコードが読みやすいかなと思っただけなんで、どっちでもいいかもです！

2023-07-09 06:15 UTC, ponsAoki commented on src/components/organisms/ProductCard.tsx
> +            <Image src={participant?.imageUrl ? participant.imageUrl : "/avatar.gif"} alt="Image Description" width={50} height={50} className="border border-gray-200 rounded-full"/>
ここ、`<PersonIcon/>`ていうコンポーネント使って欲しいです🙇

2023-07-09 17:50 UTC, nagayamajun commented on src/constants/env.ts
> +export const corporateTechUniPassword = process.env.NEXT_PUBLIC_TECH_UNI_PASSWORD;
@ponsAoki

2023-07-09 18:09 UTC, nagayamajun commented on src/components/organisms/ProductCard.tsx
> +            <Image src={participant?.imageUrl ? participant.imageUrl : "/avatar.gif"} alt="Image Description" width={50} height={50} className="border border-gray-200 rounded-full"/>
承知しました🫡

2023-07-13 14:37 UTC, ponsAoki commented on src/constants/env.ts
> +export const corporateTechUniPassword = process.env.NEXT_PUBLIC_TECH_UNI_PASSWORD;
@nagayamajun 
返信できてませんでしたごめんなさい！🙇
`corporateMessagingSenderId`自分もよくわかってないんですけど、GoogleAnalythicsと連携する時に使うなんかのIDみたいです！確かfirebaseのプロジェクト作る時に「GoogleAnalythicsとの連携をしますか？ (推奨)」みたいな感じのチェエク項目があって、そこにチェックしたから存在してる変数なんだと思います！
https://firebase.google.com/docs/analytics/get-started?hl=ja&platform=web

2023-07-15 08:43 UTC, merged