[FE]user側の画面のUI修正
nagayamajun/unite-replace-front pull request #30
Opened 2023-08-07 03:40 UTC by nagayamajun

--概要
1.sideBarに伴う画面崩れの対応
2.recruitの条件探索をrecoilを利用した方法からqueryを利用した方法に変更
3.recruitCardのデザイン変更
<img width="1728" alt="スクリーンショット 2023-08-07 12 37 14" src="https://github.com/nagayamajun/unite-replace-front/assets/85071324/3d0bf717-32c5-4e1b-8f4e-4072cadd5a43">
<img width="1728" alt="スクリーンショット 2023-08-07 12 39 06" src="https://github.com/nagayamajun/unite-replace-front/assets/85071324/fd060224-52a5-45af-9774-93b37deb4311">

2023-08-07 03:42 UTC, nagayamajun commented on src/features/recruit/components/organisms/Search/NarrowSerch.tsx
> +        router.push({
queryを用いて募集の絞り込みを行う

2023-08-07 03:43 UTC, nagayamajun commented on src/features/recruit/components/organisms/List/RecruitList.tsx
> +
queryを取得して条件分岐を行う

2023-08-07 04:17 UTC, ponsAoki requested changes
@nagayamajun 
修正ありがとうございます！
数点コメントしました！🙇

2023-08-07 04:17 UTC, ponsAoki commented on src/features/product/components/templates/UploadProduct.tsx
>              if (!result.success) return router.reload();
今回の変更範囲ではないと思うんですけど、form処理の失敗時ってリロードしない方が入力した内容が確認できて親切かなとか思うんですけどどうですかね？

2023-08-07 04:17 UTC, ponsAoki commented on src/features/recruit/components/organisms/List/RecruitList.tsx
> +      return recruit.hackthonName === name;
ハッカソン名は部分一致でヒットしてもいいかなと思いました！
(`include`や`indexof`？)

2023-08-07 04:17 UTC, ponsAoki commented on src/features/recruit/components/organisms/List/RecruitList.tsx
> +  });
ここの条件分岐、switch分の方が可読性高そう & 変更に強いかなと思いました

2023-08-07 04:17 UTC, ponsAoki commented on src/features/recruit/components/organisms/List/RecruitList.tsx
>    const user = useRecoilValue(UserState);
この`user`使われてなさそうなんで削除でお願いします

2023-08-07 04:20 UTC, ponsAoki commented
@nagayamajun 
PRはDraftのままにしておきたい感じですか？

2023-08-07 04:32 UTC, nagayamajun commented on src/features/product/components/templates/UploadProduct.tsx
>              if (!result.success) return router.reload();
あー確かにそれは間違いないですね！

2023-08-07 05:14 UTC, nagayamajun commented on src/features/recruit/components/organisms/List/RecruitList.tsx
>    const user = useRecoilValue(UserState);
すみませんここif文をコメントアウトしていてそこで使っていました🙇‍♀️
完全に見落としていたので助かりました！

2023-08-08 15:21 UTC, ponsAoki reviewed
@nagayamajun 
コメントしてるところだけリファクタしてもらえたらマージしてもらってオッケーです！

2023-08-08 15:21 UTC, ponsAoki commented on src/features/recruit/components/organisms/Search/NarrowSerch.tsx
> +        })
ここだけswitch文にしてもらうことできますか？🙏

2023-08-08 16:41 UTC, merged