productとcommentのフロント側を実装しました
nagayamajun/unite-replace-front pull request #4
Opened 2023-06-21 11:55 UTC by nagayamajun

フロント側の実装です！

2023-06-22 17:27 UTC, ponsAoki requested changes
@nagayamajun 
サーバーサイドが起動こけたのと、多分「チャットのフロントをdevelopにはmergeしたけどmainにはmergeできてなかった」且つ「このPRがmainに向けてされていた」ためにうまくブランチを自分のlocalに取り込めなかったので、エディタでコード見たりlocalで挙動確かめられたりしてないです🙇

なので、ざっとコード見た範囲で思ったことコメントしてます！

2023-06-22 17:27 UTC, ponsAoki commented on src/components/templetes/user/EditProduct.tsx
> +                  : format(new Date(product.createdAt), 'yyyy-MM-dd')
ちょっとシンプルな疑問なんですけど、Nestのserverから返ってくる日付 (Prismaに保存されてる日付？) って標準でJST (日本標準時) なんでしたっけ？

2023-06-22 17:27 UTC, ponsAoki commented on src/components/templetes/user/OwnRecruitDetail.tsx
> +                    <div className="">
こういう要素は削っても良さそう？

2023-06-22 17:27 UTC, ponsAoki commented on src/components/organisms/EditCommentModal.tsx
> +    let comment = await commentRepository.updateCommentInfo(commentId, submitData)
`const`でもいい？

2023-06-22 17:27 UTC, ponsAoki commented on src/components/templetes/user/OwnRecruitDetail.tsx
> +  const [ userRecruitParticipants , setUserRecruitParticipants ] = useState<any>()
なるべくanyは減らしたい

2023-06-22 17:27 UTC, ponsAoki commented on src/modules/auth/auth.repository.ts
> +    return {}
この辺の変更ってどういう意図がありますか？

2023-06-22 17:27 UTC, ponsAoki commented on src/modules/user-recruit-participant/userRecruitParticipant.repository.ts
> +      const userRecruitParticipants = ( await axios.post('http://localhost:8080/user-recruit-participant/find-many-by-userRecruit',  { recruitId } )).data
この辺りだけ`http://localhost:8080`をハードコーディングしちゃってる？

2023-06-22 17:31 UTC, ponsAoki commented
@nagayamajun 
フロントのPRは特に、変更した箇所の挙動確認する動画をPRに貼って欲しいです🙇 (多分動画ファイルそのままは重くて貼れないのでzipとかに圧縮して)
あと、PRに含まれる変更範囲のざっくりとしたコード説明 (ここでこういう意図があってこういうふうに実装したみたいな) をcommentしておいてもらえると助かります！(PRで主に何をしたかとか重要そうなところが分かればok)

2023-06-26 04:24 UTC, nagayamajun commented on src/modules/user-recruit-participant/userRecruitParticipant.repository.ts
> +      const userRecruitParticipants = ( await axios.post('http://localhost:8080/user-recruit-participant/find-many-by-userRecruit',  { recruitId } )).data
そこ多分recoilで管理しているaxiosInstance通さない為です！

2023-06-26 04:25 UTC, nagayamajun commented on src/modules/auth/auth.repository.ts
> +    return {}
成功した際と失敗した際にモーダルで認識してもらえるようにする為です！

2023-06-26 04:26 UTC, nagayamajun commented on src/components/templetes/user/EditProduct.tsx
> +                  : format(new Date(product.createdAt), 'yyyy-MM-dd')
だと思います！

2023-06-26 04:37 UTC, nagayamajun commented on src/components/templetes/user/OwnRecruitDetail.tsx
> +                    <div className="">
ここは参加者一覧を表示できるようにしたいのであった方が良い気がします

2023-06-26 04:42 UTC, ponsAoki commented on src/components/templetes/user/OwnRecruitDetail.tsx
> +                    <div className="">
あ、`<div className="">`みたいなぱっと見削ってもスタイル変わらなさそうな要素です

2023-06-26 04:42 UTC, ponsAoki commented on src/components/templetes/user/OwnRecruitDetail.tsx
> +                    <div className="">
@nagayamajun 
あ、`<div className="">`みたいなぱっと見削ってもスタイル変わらなさそうな要素です

2023-06-26 04:45 UTC, ponsAoki commented on src/modules/auth/auth.repository.ts
> +    return {}
`return {}`って記述しないとcompileエラー出たりしますかね？？

2023-06-26 04:49 UTC, ponsAoki commented on src/modules/user-recruit-participant/userRecruitParticipant.repository.ts
> +      const userRecruitParticipants = ( await axios.post('http://localhost:8080/user-recruit-participant/find-many-by-userRecruit',  { recruitId } )).data
@nagayamajun 
axiosInstanceはrecoilで管理しなくなってるはずなんで、他のapiコールと同じようにaxiosInstance使う形でお願いします🙇

2023-06-26 05:32 UTC, nagayamajun commented on src/components/templetes/user/OwnRecruitDetail.tsx
> +                    <div className="">
そゆことか、、
すみません理解できてませんでした🙇

2023-06-26 06:20 UTC, ponsAoki requested changes

2023-06-26 06:20 UTC, ponsAoki commented on src/components/templetes/user/RecruitDetail.tsx
> +    userRecruitParticipant
ここ、潤さんの変更範囲ではないと思いますが、letで再宣言しなくてもpropsの引数のところを分割代入でいいかなと思いました！

2023-06-26 06:20 UTC, ponsAoki commented on src/pages/recruit/[id]/recruitDetail.tsx
<img width="1440" alt="スクリーンショット 2023-06-26 15 07 07" src="https://github.com/nagayamajun/unite-replace-front/assets/99397043/1f766068-6823-4cf4-9fcf-6364a71371a2">
このpathにアクセスするとスクショみたいなエラー出たんですけど、潤さんのlocal環境でも出ますか？

2023-06-26 06:20 UTC, ponsAoki commented on src/components/templetes/user/OwnRecruitDetail.tsx
> +                <Link href={"/"} >Productページへ</Link>
ここの「Productページ」はまだできてない感じですか？

2023-06-26 06:21 UTC, ponsAoki commented on src/pages/recruit/[id]/recruitDetail.tsx
多分、RecruitDetailコンポーネントにrecruit情報をpropsとして渡せてない気がします

2023-06-26 06:21 UTC, ponsAoki commented
@nagayamajun 
数点コメントしたので確認お願いします🙇

2023-06-28 11:58 UTC, ponsAoki approved these changes
動画見れたら良かったんですけど、とりあえずokです👍

2023-06-28 11:58 UTC, ponsAoki commented on src/components/templetes/user/RecruitDetail.tsx
> +  }, [])
ここのrecruitをidで取得する処理のカスタムhook化お願いします🙇

2023-06-28 11:58 UTC, ponsAoki commented on src/components/templetes/user/MyProductAndRelatedProduct.tsx
> +      setRelatedProducts(fetchedMyProducts);
ここ両方のstateの更新でfetchedMyProductsを代入しちゃってます！

2023-06-28 12:00 UTC, ponsAoki commented
@nagayamajun 
↑のレビュー対応できますか？？言うの遅くなって申し訳ないです🙇
めっちゃ急いでるようだったら、fetchedMyProductsのところの修正だけお願いします！

2023-06-28 12:02 UTC, ponsAoki commented
> @nagayamajun ↑のレビュー対応できますか？？言うの遅くなって申し訳ないです🙇 めっちゃ急いでるようだったら、fetchedMyProductsのところの修正だけお願いします！

2023-06-28 12:16 UTC, nagayamajun commented on src/components/templetes/user/MyProductAndRelatedProduct.tsx
> +      setRelatedProducts(fetchedMyProducts);
おっとすみません完全に見落としてました🙇‍♀️

2023-06-28 12:18 UTC, merged