[FE]ランキング周りUI
nagayamajun/unite-replace-front pull request #44
Opened 2023-08-19 07:30 UTC by nagayamajun

##概要
ランキング周りのUIを作成したのとfeature構成にあわせたファイル移動を行いました

2023-08-19 08:48 UTC, ponsAoki requested changes
@nagayamajun 
実装ありがとうございます！
ランキングUIいい感じです！！
数点コメントしたので確認お願いします🙇

2023-08-19 08:48 UTC, ponsAoki commented on tsconfig.json
> +  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", "src/features/product/modules/employee-product-like"],
ここの説明お願いしてもいいですか？？

2023-08-19 08:48 UTC, ponsAoki commented on src/features/ranking/modules/period-like-sum/period-like-sum.repository.ts
> +    return periodLikeSums
moduleのapi通信はtry catchで書くに統一しましょう！(今決めました🙇)
あと、catch句で
```
if (error instanceof Error) {
      throw new Error(error.message);
 }
throw error;
```
みたいな感じでerrorのインターフェースチェックも原則しておきたいかもです！

2023-08-21 06:57 UTC, nagayamajun commented on tsconfig.json
> +  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", "src/features/product/modules/employee-product-like"],
@ponsAoki 
ここバックエンドで取り入れるの間違った感じだと思います🙇‍♀️

2023-08-21 07:00 UTC, nagayamajun commented on src/features/ranking/modules/period-like-sum/period-like-sum.repository.ts
> +    return periodLikeSums
@ponsAoki 
承知しました！

2023-08-22 13:36 UTC, ponsAoki approved these changes
@nagayamajun 
いいと思います！👍

2023-08-27 09:25 UTC, merged