[FE] Loadingと成功失敗モーダルのグローバル化(全体に適応)
nagayamajun/unite-replace-front pull request #47
Opened 2023-09-02 13:06 UTC by nagayamajun

##概要
recoilを使ってloadingを管理する方法に変更しました。

2023-09-02 13:07 UTC, nagayamajun commented on src/stores/toast/index.ts
> +export const ToastState = atom<Toast>({
成功・失敗モーダルをrecoilで管理。

2023-09-02 13:08 UTC, nagayamajun commented on src/hooks/useLoading.ts
> +  const showLoading = (): void => {
loadingを表示・非表示するカスタムフック

2023-09-02 13:08 UTC, nagayamajun commented on src/hooks/useToast.ts
> +  const showToast = ({message, style}: { message: string, style: ToastStyle }): void => {
モーダルを表示するカスタムフック

2023-09-02 13:21 UTC, nagayamajun commented on src/components/molecules/Input/PlainInput.tsx
> +const validateFileExtension = (value: any): boolean | string => {
typeがfileの時のカスタムエラーハンドリング追加

2023-09-03 04:37 UTC, nagayamajun commented on src/features/user/components/templates/UserProfile.tsx
> -import { Fragment, useEffect, useState } from "react";
可読性を上げるためにコンポーネントに切り分けました。

2023-09-03 08:04 UTC, ponsAoki requested changes
@nagayamajun 
めちゃくちゃ大掛かりなリファクタリングありがとうございます！
改善された点がすごい多くて感謝です！🙇‍♂️
まだセルフレビューしてくれてる点を中心にざっくりとしかチェックできていなんですが、数点コメントさせてもらいました🙏確認お願いします！

2023-09-03 08:04 UTC, ponsAoki commented on src/components/organisms/Loading/Loading.tsx
> +    <div className="fixed inset-0 flex items-center justify-center z-50 bg-blue-50 bg-opacity-50">
ここ、`if (!state.isLoading) return <></>;`みたいにするのもいいと思うんですけど、`ToastModal`とかのレンダリング方法に寄せて、一番親の`div`タグに`hidden={!state.isLoading}`つけるのもいいのかもなと思ったんですけどどうですかね？そんな変わらないか

2023-09-03 08:04 UTC, ponsAoki commented on src/features/auth/components/templates/SignIn.tsx
> +        style === 'success' ? 2000 : 4000
`'success'`が結構ソース内に散見される気がするんで、`STATE_SUCCESS`みたいな定数で共通化して使う方がいいかもしれませんね〜

2023-09-03 08:04 UTC, ponsAoki commented on src/components/molecules/Input/PlainInput.tsx
> +const validateFileExtension = (value: any): boolean | string => {
これいいですね！👍

2023-09-03 08:04 UTC, ponsAoki commented on src/features/user/components/organisms/EditUserInfo/inedx.tsx
> +  const { id: userId } = router.query;
この`userId`使われてなさそうなんでこの行ごと削除でお願いします🙏

2023-09-03 08:09 UTC, ponsAoki commented on src/pages/_app.tsx
>              <Component {...pageProps} />
👍

2023-09-03 11:10 UTC, nagayamajun commented on src/components/organisms/Loading/Loading.tsx
> +    <div className="fixed inset-0 flex items-center justify-center z-50 bg-blue-50 bg-opacity-50">
これ青木さんの案の方がシンプルで良いですね！！

2023-09-03 11:22 UTC, nagayamajun commented on src/features/auth/components/templates/SignIn.tsx
> +        style === 'success' ? 2000 : 4000
@ponsAoki 
ここに関してなのですが、
`'success`を`export const STATE_SUCCESS = 'success'`
みたいにする認識であってますか？？🙇‍♀️

2023-09-04 00:30 UTC, merged