[FE]いいね機能といいねした募集を一覧表示するページの実装
nagayamajun/unite-replace-front pull request #6
Opened 2023-06-29 15:25 UTC by nagayamajun

--概要
userが募集に対していいねすることができる機能を実装しました。
いいねした募集は`http://localhost:3000/recruit/likedRecruitList`に管理されるようになっています。

--やっていない事
いいねするハートを決め切ることができなかったので次のレスポンシブ対応デザイン変更のタスクでUI自体は整えます。

--動作確認動画
*いいねする
[画面収録 2023-06-30 0.24.28.mov.zip](https://github.com/nagayamajun/unite-replace-front/files/11907625/2023-06-30.0.24.28.mov.zip)
*いいね解除
[画面収録 2023-06-30 0.20.44.mov.zip](https://github.com/nagayamajun/unite-replace-front/files/11907596/2023-06-30.0.20.44.mov.zip)

2023-06-30 16:43 UTC, ponsAoki requested changes
@nagayamajun 
実装と動画もありがとうございます！！
数点コメントしました確認お願いします🙇‍♂️

2023-06-30 16:43 UTC, ponsAoki commented on src/components/templetes/user/AddRecruit.tsx
> +    console.log
珍しい残り方してるんですけど削除お願いしますw

2023-06-30 16:43 UTC, ponsAoki commented on src/components/templetes/user/LikedRecruitList.tsx
> +  }, [])
ここカスタムフックに切り出したいですね！

2023-06-30 16:43 UTC, ponsAoki commented on src/modules/user-recruit-like/userToRecruitLikeRepository.tsx
> +      throw new Error(`いいねすることに失敗しました。 ${error}`)
後出しで申し訳ないんですけど、この辺のエラーハンドリングを最新のdevelopブランチの`auth.repository.ts`を参考に実装お願いします🙇‍♂️🙇‍♂️

2023-06-30 16:43 UTC, ponsAoki commented on src/pages/recruit/likedRecruitList.tsx
> +  <><LikedRecruitList /></>
`() => <LikedRecruitList />`で良さげ

2023-07-02 05:25 UTC, nagayamajun commented on src/modules/user-recruit-like/userToRecruitLikeRepository.tsx
> +      throw new Error(`いいねすることに失敗しました。 ${error}`)
@ponsAoki 
ここに関してなんですがいいねに失敗した際にモーダルを表示するという認識であってますか？

2023-07-02 05:46 UTC, ponsAoki commented on src/modules/user-recruit-like/userToRecruitLikeRepository.tsx
> +      throw new Error(`いいねすることに失敗しました。 ${error}`)
そうですね！失敗した時だけモーダル欲しいかもですね。でもそれもそれでベストかはわかんないですね〜

2023-07-02 05:46 UTC, ponsAoki commented on src/modules/user-recruit-like/userToRecruitLikeRepository.tsx
> +      throw new Error(`いいねすることに失敗しました。 ${error}`)
@nagayamajun 
そうですね！失敗した時だけモーダル欲しいかもですね。でもそれもそれでベストかはわかんないですね〜

2023-07-05 11:13 UTC, closed without merging